version: '3.8'
services:
  spotitube_token:
    container_name: spotitube_token
    networks:
      - internal
    build:
      context: ./token/
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      SPOTIPY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIPY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIPY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_SCOPES: ${SPOTIFY_SCOPES}
      SPOTIFY_CODE: ${SPOTIFY_CODE}
    restart: unless-stopped
  spotitube_songs:
    container_name: spotitube_songs
    networks:
      - internal
    build:
      context: ./songs/
      dockerfile: Dockerfile
    restart: unless-stopped
  spotitube_manager:
    container_name: spotitube_manager
    networks:
      - internal
    environment:
      PLAYLIST_FOLDER: ${PLAYLIST_FOLDER}
      PLAYLIST_HISTORY: ${PLAYLIST_HISTORY}
      PORT: ${PORT}
      MAX_TRACK_COUNT: ${MAX_TRACK_COUNT}
      TRACK_DELAY: ${TRACK_DELAY}
      GENERATE_PLAYLISTS: ${GENERATE_PLAYLISTS}
    build:
      context: ./manager/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ~/playlists:/app/playlists
  spotitube_bot:
    container_name: spotitube_bot
    networks:
      - internal
      - web
    expose:
      - "80"
      - "443"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_COMMAND_PREFIX: ${BOT_COMMAND_PREFIX}
    build:
      context: ./bot/
      dockerfile: Dockerfile
    restart: unless-stopped
networks:
  internal:
    name: internal
  web:
    external:
      name: ${EXTERNAL_NETWORK_NAME}

