version: '3.8'
services:
  spotitube_token:
    container_name: spotitube_token
    networks:
      - spotitube
    build:
      context: ./token/
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      SPOTIPY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIPY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIPY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_SCOPES: ${SPOTIFY_SCOPES}
      SPOTIFY_CODE: ${SPOTIFY_CODE}
    restart: unless-stopped
  spotitube_songs:
    container_name: spotitube_songs
    networks:
      - spotitube
    build:
      context: ./songs/
      dockerfile: Dockerfile
    restart: unless-stopped
  spotitube_manager:
    container_name: spotitube_manager
    networks:
      - spotitube
    environment:
      PLAYLIST_FOLDER: /app/playlists
      PLAYLIST_HISTORY: ${PLAYLIST_HISTORY:-False}
      PORT: ${PORT:-80}
      MAX_TRACK_COUNT: ${MAX_TRACK_COUNT:-50}
      TRACK_DELAY: ${TRACK_DELAY:-10}
      GENERATE_PLAYLISTS: ${GENERATE_PLAYLISTS:-True}
    build:
      context: ./manager/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${PLAYLIST_FOLDER:-./}:/app/playlists
networks:
  spotitube:
    name: spotitube
  web:
    external:
      name: ${EXTERNAL_NETWORK_NAME}

