version: '3.8'
services:
  spotitube_token:
    container_name: spotitube_token
    networks:
      - internal
    build:
      context: ./token/
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_CODE: ${SPOTIFY_CODE}
    restart: unless-stopped
  spotitube_songs:
    container_name: spotitube_songs
    networks:
      - internal
    build:
      context: ./songs/
      dockerfile: Dockerfile
    restart: unless-stopped
  spotitube_manager:
    container_name: spotitube_manager
    networks:
      - internal
    environment:
      PLAYLIST_FOLDER: ./playlists
    build:
      context: ./manager/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ~/playlists:/app/playlists
  spotitube_bot:
    container_name: spotitube_bot
    networks:
      - internal
      - web
    expose:
      - "80"
      - "443"
    environment:
      TOKEN: ${TOKEN}
    build:
      context: ./bot/
      dockerfile: Dockerfile
    restart: unless-stopped
networks:
  internal:
    name: internal
  web:
    external:
      name: web-routing_web

